language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t dockeralex23/react-test -f ./client/Dockerfile.dev ./client

scripts:
 - docker run dockeralex23/react-test npm test -- --coverage

after_success:
 - docker build -t dockeralex23/multi-client ./client
 - docker build -t dockeralex23/multi-nginx ./nginx
 - docker build -t dockeralex23/multi-server ./server
 - docker build -t dockeralex23/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push dockeralex23/multi-client
 - docker push dockeralex23/multi-nginx
 - docker push dockeralex23/multi-server
 - docker push dockeralex23/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-523525258587
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
