language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t dockeralex23/react-test -f ./client/Dockerfile.dev ./client

scripts:
 - docker run dockeralex23/react-test npm test -- --coverage

after_sucess:
 - docker build -t dockeralex23/multi-client ./client
 - docker build -t dockeralex23/multi-nginx ./nginx
 - docker build -t dockeralex23/multi-server ./server
 - docker build -t dockeralex23/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push dockeralex23/multi-client
 - docker push dockeralex23/multi-nginx
 - docker push dockeralex23/multi-server
 - docker push dockeralex23/multi-worker

